#!/usr/bin/env bash
# Regenerates contract artifacts for all four languages from
# packages/contracts/schemas (the single source of truth).
#
# Outputs (all committed, all covered by the CI drift gate):
#   apps/web/src/contracts/gen/*.d.ts            TypeScript types
#   apps/ml-python/src/models/gen/*.py           Pydantic models
#   apps/crawler-go/internal/contracts/gen/*.go  Go structs
#   apps/engine-rust/crates/loom-contracts/src/gen/*.rs  Rust types (typify)
#   */gen/schemas/*.schema.json                  verbatim schema copies, embedded
#                                                by each service for runtime validation
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
SCHEMAS="$ROOT/packages/contracts/schemas"
CODEGEN="$ROOT/packages/contracts/codegen"

# shellcheck source=versions.env
source "$CODEGEN/versions.env"

TS_OUT="$ROOT/apps/web/src/contracts/gen"
PY_OUT="$ROOT/apps/ml-python/src/models/gen"
GO_OUT="$ROOT/apps/crawler-go/internal/contracts/gen"
# `gen` is a reserved keyword in Rust edition 2024, so the Rust module is `generated`
RS_OUT="$ROOT/apps/engine-rust/crates/loom-contracts/src/generated"

GOJSONSCHEMA="${GOJSONSCHEMA:-$HOME/go/bin/go-jsonschema}"
DATAMODEL_CODEGEN="${DATAMODEL_CODEGEN:-$CODEGEN/.venv/bin/datamodel-codegen}"

need() {
  command -v "$1" >/dev/null 2>&1 || { echo "ERROR: missing tool: $1 ($2)" >&2; exit 1; }
}
need npx "npm ci in packages/contracts/codegen"
need cargo-typify "cargo install cargo-typify --locked --version $CARGO_TYPIFY_VERSION (or: make setup-codegen)"
[[ -x "$GOJSONSCHEMA" ]] || { echo "ERROR: missing $GOJSONSCHEMA (go install $GO_JSONSCHEMA_MODULE@$GO_JSONSCHEMA_VERSION, or: make setup-codegen)" >&2; exit 1; }
[[ -x "$DATAMODEL_CODEGEN" ]] || { echo "ERROR: missing $DATAMODEL_CODEGEN (make setup-codegen)" >&2; exit 1; }
# `command -v rustfmt` succeeds even when the component is absent — rustup
# ships a proxy that fails only on invocation. Probe the real thing.
rustfmt --version >/dev/null 2>&1 || {
  echo "ERROR: rustfmt unavailable (rustup component add rustfmt)" >&2; exit 1; }

# Refuse to generate with a drifted toolchain — output differs across versions
actual_typify="$(cargo-typify --help >/dev/null 2>&1; cargo typify --version 2>/dev/null | awk '{print $2}')"
if [[ -n "$actual_typify" && "$actual_typify" != "$CARGO_TYPIFY_VERSION" ]]; then
  echo "ERROR: cargo-typify $actual_typify installed, need $CARGO_TYPIFY_VERSION (see versions.env)" >&2
  exit 1
fi
actual_dmc="$("$DATAMODEL_CODEGEN" --version 2>/dev/null | awk '{print $NF}')"
if [[ -n "$actual_dmc" && "$actual_dmc" != "$DATAMODEL_CODEGEN_VERSION" ]]; then
  echo "ERROR: datamodel-codegen $actual_dmc installed, need $DATAMODEL_CODEGEN_VERSION (see versions.env)" >&2
  exit 1
fi

mkdir -p "$TS_OUT" "$PY_OUT" "$GO_OUT" "$RS_OUT"

# ---- verbatim schema copies for runtime validation (each service embeds its own) ----
for out in "$TS_OUT" "$PY_OUT" "$GO_OUT" "$RS_OUT"; do
  rm -rf "$out/schemas"
  mkdir -p "$out/schemas"
  cp "$SCHEMAS"/*.schema.json "$out/schemas/"
done

schema_files=("$SCHEMAS"/*.schema.json)

# ---- TypeScript (json-schema-to-typescript) ----
for f in "${schema_files[@]}"; do
  base="$(basename "$f" .schema.json)"           # e.g. crawl_record.v1
  out="$TS_OUT/${base}.d.ts"
  npx --prefix "$CODEGEN" json2ts "$f" \
    --bannerComment "/* GENERATED by packages/contracts/codegen/generate.sh — DO NOT EDIT */" \
    --additionalProperties false > "$out"
done

# ---- Python (datamodel-code-generator -> Pydantic v2) ----
"$DATAMODEL_CODEGEN" \
  --input "$SCHEMAS" \
  --input-file-type jsonschema \
  --output "$PY_OUT" \
  --output-model-type pydantic_v2.BaseModel \
  --disable-timestamp \
  --use-schema-description \
  --target-python-version 3.12
touch "$PY_OUT/__init__.py"

# ---- Go (go-jsonschema) ----
for f in "${schema_files[@]}"; do
  base="$(basename "$f" .schema.json)"
  gofile="$GO_OUT/$(echo "$base" | tr '.' '_').go"
  "$GOJSONSCHEMA" -p gen --only-models --struct-name-from-title -o "$gofile" "$f"
done

# ---- Rust (typify) ----
rs_mods=()
for f in "${schema_files[@]}"; do
  base="$(basename "$f" .schema.json)"
  mod="$(echo "$base" | tr '.' '_')"             # crawl_record_v1
  cargo-typify typify "$f" --output "$RS_OUT/${mod}.rs" >/dev/null
  # typify's own formatting is not rustfmt-clean for deeply nested generic
  # bounds (builder setters over Option<DateTime> / Vec<NestedItem>), and
  # `cargo fmt --check` gates CI. Normalize here so the committed output is
  # both generated and fmt-clean; never hand-edit it to achieve this.
  #
  # CAVEAT: rustfmt is the one tool here NOT pinned by versions.env — CI floats
  # on stable. Style edition 2024 carries a formatting-stability guarantee, so
  # the risk is low, but if the drift gate ever fails with no schema change,
  # suspect a rustfmt release before you suspect the schemas.
  rustfmt --edition 2024 "$RS_OUT/${mod}.rs"
  rs_mods+=("$mod")
done
{
  echo "// GENERATED by packages/contracts/codegen/generate.sh — DO NOT EDIT"
  for m in "${rs_mods[@]}"; do
    # typify output uses unwrap() on compile-time-known-good regexes
    echo "#[allow(clippy::unwrap_used)]"
    echo "pub mod ${m};"
  done
} > "$RS_OUT/mod.rs"

echo "contracts: generated $(ls "$SCHEMAS" | wc -l) schema(s) for ts/py/go/rs"
